version: '3.9'
services:
  jupyterlab:
    image: my_ds_env:latest
    deploy:
      resources:
        reservations:
          devices:
          - 'driver': 'nvidia'
            'capabilities': ['gpu']
    container_name: jupyterlab
    ports:
      - '8888:8888'
    volumes:
      - '.:/workspace'
    command: jupyter lab
    tty: true
    stdin_open: true